In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("demografia.csv", sep=";")
print(df.columns)
df

Index(['Municipios', 'Distritos', 'Secciones', 'Indicadores demográficos',
       'Periodo', 'Total'],
      dtype='str')

,Municipios,Distritos,Secciones,Indicadores demográficos,Periodo,Total
0,"28001 Acebeda, La",NaN,NaN,Edad media de la población,2023,"59,8"
1,"28001 Acebeda, La",NaN,NaN,Edad media de la población,2022,"62,2"
2,"28001 Acebeda, La",NaN,NaN,Edad media de la población,2021,"59,2"
3,"28001 Acebeda, La",NaN,NaN,Edad media de la población,2020,"59,5"
4,"28001 Acebeda, La",NaN,NaN,Edad media de la población,2019,.
...,...,...,...,...,...,...
312853,28903 Tres Cantos,2890301 Tres Cantos distrito 01,2890301027 Tres Cantos sección 01027,Porcentaje de población española,2019,NaN
312854,28903 Tres Cantos,2890301 Tres Cantos distrito 01,2890301027 Tres Cantos sección 01027,Porcentaje de población española,2018,NaN
312855,28903 Tres Cantos,2890301 Tres Cantos distrito 01,2890301027 Tres Cantos sección 01027,Porcentaje de población española,2017,NaN
312856,28903 Tres Cantos,2890301 Tres Cantos distrito 01,2890301027 Tres Cantos sección 01027,Porcentaje de población española,2016,NaN
312857,28903 Tres Cantos,2890301 Tres Cantos distrito 01,2890301027 Tres Cantos sección 01027,Porcentaje de población española,2015,NaN

In [3]:
df_filtrado = df[df["Municipios"].str.contains("^28079 Madrid", case=False, na=False)]

df_filtrado

,Municipios,Distritos,Secciones,Indicadores demográficos,Periodo,Total
81648,28079 Madrid,NaN,NaN,Edad media de la población,2023,"43,9"
81649,28079 Madrid,NaN,NaN,Edad media de la población,2022,"43,9"
81650,28079 Madrid,NaN,NaN,Edad media de la población,2021,"44,0"
81651,28079 Madrid,NaN,NaN,Edad media de la población,2020,"43,8"
81652,28079 Madrid,NaN,NaN,Edad media de la población,2019,"43,6"
...,...,...,...,...,...,...
240088,28079 Madrid,2807921 Madrid distrito 21,2807921034 Madrid sección 21034,Porcentaje de población española,2019,NaN
240089,28079 Madrid,2807921 Madrid distrito 21,2807921034 Madrid sección 21034,Porcentaje de población española,2018,NaN
240090,28079 Madrid,2807921 Madrid distrito 21,2807921034 Madrid sección 21034,Porcentaje de población española,2017,NaN
240091,28079 Madrid,2807921 Madrid distrito 21,2807921034 Madrid sección 21034,Porcentaje de población española,2016,NaN
240092,28079 Madrid,2807921 Madrid distrito 21,2807921034 Madrid sección 21034,Porcentaje de población española,2015,NaN

In [4]:
df_filtrado = df_filtrado[df_filtrado['Periodo'].between(2015,2022)]
print(df_filtrado.isna().sum())  
df_filtrado

Municipios                     0
Distritos                     56
Secciones                   1232
Indicadores demográficos       0
Periodo                        0
Total                       3073
dtype: int64

,Municipios,Distritos,Secciones,Indicadores demográficos,Periodo,Total
81649,28079 Madrid,NaN,NaN,Edad media de la población,2022,"43,9"
81650,28079 Madrid,NaN,NaN,Edad media de la población,2021,"44,0"
81651,28079 Madrid,NaN,NaN,Edad media de la población,2020,"43,8"
81652,28079 Madrid,NaN,NaN,Edad media de la población,2019,"43,6"
81653,28079 Madrid,NaN,NaN,Edad media de la población,2018,"43,6"
...,...,...,...,...,...,...
240088,28079 Madrid,2807921 Madrid distrito 21,2807921034 Madrid sección 21034,Porcentaje de población española,2019,NaN
240089,28079 Madrid,2807921 Madrid distrito 21,2807921034 Madrid sección 21034,Porcentaje de población española,2018,NaN
240090,28079 Madrid,2807921 Madrid distrito 21,2807921034 Madrid sección 21034,Porcentaje de población española,2017,NaN
240091,28079 Madrid,2807921 Madrid distrito 21,2807921034 Madrid sección 21034,Porcentaje de población española,2016,NaN
240092,28079 Madrid,2807921 Madrid distrito 21,2807921034 Madrid sección 21034,Porcentaje de población española,2015,NaN

In [5]:
df_filtrado['Indicadores demográficos'].unique()

<ArrowStringArray>
[              'Edad media de la población',
 'Porcentaje de población menor de 18 años',
 'Porcentaje de población de 65 y más años',
                   'Tamaño medio del hogar',
      'Porcentaje de hogares unipersonales',
                                'Población',
         'Porcentaje de población española']
Length: 7, dtype: str

In [6]:
df_filtrado = df_filtrado.drop(columns=['Municipios', 'Distritos'])
df_filtrado = df_filtrado.rename(columns={'Secciones': 'COD_SEC_MADRID', 'Periodo': 'Año', 'Indicadores demográficos': 'indicadores'})

In [7]:
df_dem = df_filtrado.copy()
df_sec_dem = df_dem[df_dem["COD_SEC_MADRID"].notna()].copy()

In [8]:
df_sec_dem

,COD_SEC_MADRID,indicadores,Año,Total
81775,2807901001 Madrid sección 01001,Edad media de la población,2022,"47,2"
81776,2807901001 Madrid sección 01001,Edad media de la población,2021,"47,3"
81777,2807901001 Madrid sección 01001,Edad media de la población,2020,"47,1"
81778,2807901001 Madrid sección 01001,Edad media de la población,2019,"46,8"
81779,2807901001 Madrid sección 01001,Edad media de la población,2018,"46,9"
...,...,...,...,...
240088,2807921034 Madrid sección 21034,Porcentaje de población española,2019,NaN
240089,2807921034 Madrid sección 21034,Porcentaje de población española,2018,NaN
240090,2807921034 Madrid sección 21034,Porcentaje de población española,2017,NaN
240091,2807921034 Madrid sección 21034,Porcentaje de población española,2016,NaN
240092,2807921034 Madrid sección 21034,Porcentaje de población española,2015,NaN

In [9]:
nombres = {'Edad media de la población': 'edad_media',
 'Porcentaje de población menor de 18 años':'pct_menor18',
 'Porcentaje de población de 65 y más años': 'pct_65mas',
                   'Tamaño medio del hogar':'tam_hogar',
      'Porcentaje de hogares unipersonales':'pct_unipersonal',
                                'Población': 'poblacion',
         'Porcentaje de población española': 'pct_española'}

df_sec_dem['indicadores'] = df_sec_dem['indicadores'].map(nombres)
df_sec_dem

                         COD_SEC_MADRID   indicadores   Año Total
81775   2807901001 Madrid sección 01001    edad_media  2022  47,2
81776   2807901001 Madrid sección 01001    edad_media  2021  47,3
81777   2807901001 Madrid sección 01001    edad_media  2020  47,1
81778   2807901001 Madrid sección 01001    edad_media  2019  46,8
81779   2807901001 Madrid sección 01001    edad_media  2018  46,9
...                                 ...           ...   ...   ...
240088  2807921034 Madrid sección 21034  pct_española  2019   NaN
240089  2807921034 Madrid sección 21034  pct_española  2018   NaN
240090  2807921034 Madrid sección 21034  pct_española  2017   NaN
240091  2807921034 Madrid sección 21034  pct_española  2016   NaN
240092  2807921034 Madrid sección 21034  pct_española  2015   NaN

[139608 rows x 4 columns]

In [10]:
df_sec_dem['COD_SEC_MADRID'] = df_sec_dem['COD_SEC_MADRID'].astype(str).str[:10]
df_sec_dem = df_sec_dem[df_sec_dem['indicadores'] != 'pct_española']
df_sec_dem

       COD_SEC_MADRID indicadores   Año Total
81775      2807901001  edad_media  2022  47,2
81776      2807901001  edad_media  2021  47,3
81777      2807901001  edad_media  2020  47,1
81778      2807901001  edad_media  2019  46,8
81779      2807901001  edad_media  2018  46,9
...               ...         ...   ...   ...
240079     2807921034   poblacion  2019   NaN
240080     2807921034   poblacion  2018   NaN
240081     2807921034   poblacion  2017   NaN
240082     2807921034   poblacion  2016   NaN
240083     2807921034   poblacion  2015   NaN

[119664 rows x 4 columns]

In [11]:
print(df_sec_dem["indicadores"].unique())
for ind in df_sec_dem["indicadores"].unique():
    print(ind, df_sec_dem.loc[df_sec_dem["indicadores"] == ind, "Total"].dropna().head().tolist())

<ArrowStringArray>
[     'edad_media',     'pct_menor18',       'pct_65mas',       'tam_hogar',
 'pct_unipersonal',       'poblacion']
Length: 6, dtype: str
edad_media ['47,2', '47,3', '47,1', '46,8', '46,9']
pct_menor18 ['8,7', '8,6', '9,9', '9,7', '10,8']
pct_65mas ['23,5', '23,8', '23,7', '22,3', '23,5']
tam_hogar ['2,1', '2,0', '2,0', '2,1', '2,1']
pct_unipersonal ['43,4', '43,6', '42,9', '42,1', '41,3']
poblacion ['1.147', '1.126', '1.139', '1.172', '1.134']

In [12]:
df_sec_dem['Total'] = df_sec_dem['Total'].astype(str).str.strip()
df_sec_dem['Total'] = np.where(
    df_sec_dem['indicadores'] == 'poblacion',
    df_sec_dem['Total'].str.replace('.', '', regex=False),
    df_sec_dem['Total'].str.replace(',', '.', regex=False))
df_sec_dem['Total'] = pd.to_numeric(df_sec_dem['Total'], errors='coerce')
df_sec_dem

       COD_SEC_MADRID indicadores   Año  Total
81775      2807901001  edad_media  2022   47.2
81776      2807901001  edad_media  2021   47.3
81777      2807901001  edad_media  2020   47.1
81778      2807901001  edad_media  2019   46.8
81779      2807901001  edad_media  2018   46.9
...               ...         ...   ...    ...
240079     2807921034   poblacion  2019    NaN
240080     2807921034   poblacion  2018    NaN
240081     2807921034   poblacion  2017    NaN
240082     2807921034   poblacion  2016    NaN
240083     2807921034   poblacion  2015    NaN

[119664 rows x 4 columns]

In [13]:
df_sec_dem = (df_sec_dem.groupby(["COD_SEC_MADRID", "Año", "indicadores"])["Total"].first().unstack("indicadores").reset_index())
print(df_sec_dem.shape)

(19944, 8)

In [14]:
df_sec_dem["pct_18_64"] = 100 - df_sec_dem["pct_menor18"] - df_sec_dem["pct_65mas"]
df_dem_sec_madrid = df_sec_dem

In [15]:
df_dem_sec_madrid = df_dem_sec_madrid.drop(columns=['pct_menor18', 'pct_18_64'])
df_dem_sec_madrid

indicadores,COD_SEC_MADRID,Año,edad_media,pct_65mas,pct_unipersonal,poblacion,tam_hogar
0,2807901001,2015,46.3,23.0,42.4,1109.0,2.1
1,2807901001,2016,46.8,23.5,42.7,1083.0,2.1
2,2807901001,2017,46.7,23.7,43.3,1098.0,2.1
3,2807901001,2018,46.9,23.5,41.3,1134.0,2.1
4,2807901001,2019,46.8,22.3,42.1,1172.0,2.1
...,...,...,...,...,...,...,...
19939,2807921034,2018,NaN,NaN,NaN,NaN,NaN
19940,2807921034,2019,NaN,NaN,NaN,NaN,NaN
19941,2807921034,2020,NaN,NaN,NaN,NaN,NaN
19942,2807921034,2021,NaN,NaN,NaN,NaN,NaN
19943,2807921034,2022,37.3,8.9,20.4,1401.0,2.9