In [1]:
import pandas as pd
import requests

In [2]:
url1 = 'https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/31097?tip=A&tv=847:&date=20150101:20150101'
api_sec = requests.get(url1)
datos_json1 = api_sec.json()
df = pd.DataFrame(datos_json1)
df.head()

,COD,Nombre,T3_Unidad,T3_Escala,Data
0,ADRH65783,"Acebeda, La sección 01001. Dato base. Renta ne...",Euros,,"[{'Fecha': '2015-01-01T00:00:00.000+01:00', 'T..."
1,ADRH65782,"Acebeda, La sección 01001. Dato base. Renta ne...",Euros,,"[{'Fecha': '2015-01-01T00:00:00.000+01:00', 'T..."
2,ADRH9802887,"Acebeda, La sección 01001. Dato base. Media de...",Euros,,"[{'Fecha': '2015-01-01T00:00:00.000+01:00', 'T..."
3,ADRH9499057,"Acebeda, La sección 01001. Dato base. Mediana ...",Euros,,"[{'Fecha': '2015-01-01T00:00:00.000+01:00', 'T..."
4,ADRH9499055,"Acebeda, La sección 01001. Dato base. Renta br...",Porcentaje,,"[{'Fecha': '2015-01-01T00:00:00.000+01:00', 'T..."

In [3]:
df_expandido = df.explode("Data").copy()
df_expandido["Año"] = df_expandido["Data"].str["Anyo"].astype("Int64")
df_expandido["Valor"] = df_expandido["Data"].str["Valor"].astype(float)
df_expandido.head()

,COD,Nombre,T3_Unidad,T3_Escala,Data,Año,Valor
0,ADRH65783,"Acebeda, La sección 01001. Dato base. Renta ne...",Euros,,"{'Fecha': '2015-01-01T00:00:00.000+01:00', 'T3...",2015,NaN
1,ADRH65782,"Acebeda, La sección 01001. Dato base. Renta ne...",Euros,,"{'Fecha': '2015-01-01T00:00:00.000+01:00', 'T3...",2015,NaN
2,ADRH9802887,"Acebeda, La sección 01001. Dato base. Media de...",Euros,,"{'Fecha': '2015-01-01T00:00:00.000+01:00', 'T3...",2015,NaN
3,ADRH9499057,"Acebeda, La sección 01001. Dato base. Mediana ...",Euros,,"{'Fecha': '2015-01-01T00:00:00.000+01:00', 'T3...",2015,NaN
4,ADRH9499055,"Acebeda, La sección 01001. Dato base. Renta br...",Porcentaje,,"{'Fecha': '2015-01-01T00:00:00.000+01:00', 'T3...",2015,NaN

In [4]:
filtro_madrid = df_expandido["Nombre"].str.contains("^Madrid", case=False, na=False)
filtro_T3unidad = df_expandido["T3_Unidad"].str.strip() == "Euros"
df_sec_filtrado = df_expandido[filtro_madrid & filtro_T3unidad].copy()

In [5]:
separacion_nombre = df_sec_filtrado["Nombre"].str.split(".", n=1, expand=True)
df_sec_filtrado["Seccion madrid"] = separacion_nombre[0].str.strip()
df_sec_filtrado["Dato base"] = separacion_nombre[1].str.strip()

In [6]:
indicadores_datobase = ["Dato base. Renta neta media por persona.","Dato base. Renta neta media por hogar."]
filtro_rentas_sec = df_sec_filtrado["Dato base"].isin(indicadores_datobase)
df_sec_filtrado = df_sec_filtrado[filtro_rentas_sec]
df_sec_filtrado['Seccion_id'] = df_sec_filtrado['Seccion madrid'].str[-5:]
df_sec_filtrado

,COD,Nombre,T3_Unidad,T3_Escala,Data,Año,Valor,Seccion madrid,Dato base,Seccion_id
6648,ADRH20975,Madrid sección 01001. Dato base. Renta neta me...,Euros,,"{'Fecha': '2015-01-01T00:00:00.000+01:00', 'T3...",2015,22948.0,Madrid sección 01001,Dato base. Renta neta media por persona.,01001
6649,ADRH20974,Madrid sección 01001. Dato base. Renta neta me...,Euros,,"{'Fecha': '2015-01-01T00:00:00.000+01:00', 'T3...",2015,49363.0,Madrid sección 01001,Dato base. Renta neta media por hogar.,01001
6654,ADRH20973,Madrid sección 01002. Dato base. Renta neta me...,Euros,,"{'Fecha': '2015-01-01T00:00:00.000+01:00', 'T3...",2015,15045.0,Madrid sección 01002,Dato base. Renta neta media por persona.,01002
6655,ADRH20972,Madrid sección 01002. Dato base. Renta neta me...,Euros,,"{'Fecha': '2015-01-01T00:00:00.000+01:00', 'T3...",2015,29040.0,Madrid sección 01002,Dato base. Renta neta media por hogar.,01002
6660,ADRH20971,Madrid sección 01003. Dato base. Renta neta me...,Euros,,"{'Fecha': '2015-01-01T00:00:00.000+01:00', 'T3...",2015,15177.0,Madrid sección 01003,Dato base. Renta neta media por persona.,01003
...,...,...,...,...,...,...,...,...,...,...
21589,ADRH40872,Madrid sección 21032. Dato base. Renta neta me...,Euros,,"{'Fecha': '2015-01-01T00:00:00.000+01:00', 'T3...",2015,55962.0,Madrid sección 21032,Dato base. Renta neta media por hogar.,21032
21594,ADRH7226132,Madrid sección 21033. Dato base. Renta neta me...,Euros,,NaN,<NA>,NaN,Madrid sección 21033,Dato base. Renta neta media por persona.,21033
21595,ADRH7226131,Madrid sección 21033. Dato base. Renta neta me...,Euros,,NaN,<NA>,NaN,Madrid sección 21033,Dato base. Renta neta media por hogar.,21033
21600,ADRH10218871,Madrid sección 21034. Dato base. Renta neta me...,Euros,,NaN,<NA>,NaN,Madrid sección 21034,Dato base. Renta neta media por persona.,21034
21601,ADRH10218872,Madrid sección 21034. Dato base. Renta neta me...,Euros,,NaN,<NA>,NaN,Madrid sección 21034,Dato base. Renta neta media por hogar.,21034

In [7]:
columnas_drop1 = ["Data", "T3_Escala", "T3_Unidad", "Nombre", "Seccion madrid"]
df_madrid_seccion_2015 = df_sec_filtrado.drop(columns=columnas_drop1).rename(columns={"Fecha": "Año"})
df_madrid_seccion_2015.head()

,COD,Año,Valor,Dato base,Seccion_id
6648,ADRH20975,2015,22948.0,Dato base. Renta neta media por persona.,01001
6649,ADRH20974,2015,49363.0,Dato base. Renta neta media por hogar.,01001
6654,ADRH20973,2015,15045.0,Dato base. Renta neta media por persona.,01002
6655,ADRH20972,2015,29040.0,Dato base. Renta neta media por hogar.,01002
6660,ADRH20971,2015,15177.0,Dato base. Renta neta media por persona.,01003

In [1]:
import pandas as pd
import requests

In [2]:
url2015 = 'https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/31097?tip=A&tv=847:&date=20150101:20150101'
url2016 = 'https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/31097?tip=A&tv=847:&date=20160101:20160101'
url2017 = 'https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/31097?tip=A&tv=847:&date=20170101:20170101'
url2018 = 'https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/31097?tip=A&tv=847:&date=20180101:20180101'
url2019 = 'https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/31097?tip=A&tv=847:&date=20190101:20190101'
url2020 = 'https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/31097?tip=A&tv=847:&date=20200101:20200101'
url2021 = 'https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/31097?tip=A&tv=847:&date=20210101:20210101'
url2022 = 'https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/31097?tip=A&tv=847:&date=20220101:20220101'

In [3]:
def procesar_datos_ine(url2016):
    api_sec = requests.get(url2016)
    datos_json = api_sec.json()
    df = pd.DataFrame(datos_json)

    df_expandido = df.explode("Data").copy()

    df_expandido["Año"] = df_expandido["Data"].str["Anyo"].astype("Int64")
    df_expandido["Valor"] = df_expandido["Data"].str["Valor"].astype(float)

    filtro_madrid = df_expandido["Nombre"].str.contains("^Madrid", case=False, na=False)
    filtro_T3unidad = df_expandido["T3_Unidad"].str.strip() == "Euros"
    df_sec_filtrado = df_expandido[filtro_madrid & filtro_T3unidad].copy()

    separacion_nombre = df_sec_filtrado["Nombre"].str.split(".", n=1, expand=True)
    df_sec_filtrado["Seccion madrid"] = separacion_nombre[0].str.strip()
    df_sec_filtrado["Dato base"] = separacion_nombre[1].str.strip()

    indicadores_datobase = ["Dato base. Renta neta media por persona.", "Dato base. Renta neta media por hogar.",]
    filtro_rentas_sec = df_sec_filtrado["Dato base"].isin(indicadores_datobase)
    df_sec_filtrado = df_sec_filtrado[filtro_rentas_sec]
    df_sec_filtrado["Seccion censal"] = df_sec_filtrado["Seccion madrid"].str[-5:]
    

    columnas_drop1 = ["Data", "T3_Escala", "T3_Unidad", "Nombre", "Seccion madrid"]
    df_madrid_seccion = df_sec_filtrado.drop(columns=columnas_drop1).rename(columns={"Fecha": "Año"})

    return df_madrid_seccion

In [4]:
df_madrid_seccion_2015 = procesar_datos_ine(url2015)
df_madrid_seccion_2016 = procesar_datos_ine(url2016)
df_madrid_seccion_2017 = procesar_datos_ine(url2017)
df_madrid_seccion_2018 = procesar_datos_ine(url2018)
df_madrid_seccion_2019 = procesar_datos_ine(url2019)
df_madrid_seccion_2020 = procesar_datos_ine(url2020)
df_madrid_seccion_2021 = procesar_datos_ine(url2021)
df_madrid_seccion_2022 = procesar_datos_ine(url2022)

In [6]:
tablas = [df_madrid_seccion_2015, df_madrid_seccion_2016, df_madrid_seccion_2017, df_madrid_seccion_2018, df_madrid_seccion_2019, df_madrid_seccion_2020, df_madrid_seccion_2021, df_madrid_seccion_2022]
df_madrid_seccion_completo = pd.concat(tablas, axis=0, ignore_index=True)

In [7]:
df_madrid_seccion_completo

,COD,Año,Valor,Dato base,Seccion censal
0,ADRH20975,2015,22948.0,Dato base. Renta neta media por persona.,01001
1,ADRH20974,2015,49363.0,Dato base. Renta neta media por hogar.,01001
2,ADRH20973,2015,15045.0,Dato base. Renta neta media por persona.,01002
3,ADRH20972,2015,29040.0,Dato base. Renta neta media por hogar.,01002
4,ADRH20971,2015,15177.0,Dato base. Renta neta media por persona.,01003
...,...,...,...,...,...
39883,ADRH40872,2022,69852.0,Dato base. Renta neta media por hogar.,21032
39884,ADRH7226132,2022,14174.0,Dato base. Renta neta media por persona.,21033
39885,ADRH7226131,2022,34040.0,Dato base. Renta neta media por hogar.,21033
39886,ADRH10218871,2022,16796.0,Dato base. Renta neta media por persona.,21034
39887,ADRH10218872,2022,49019.0,Dato base. Renta neta media por hogar.,21034

In [8]:
df_madrid_seccion_completo['Año'].isna().sum()

np.int64(876)

In [ ]:
df_madrid_seccion_completo["tipo"] = df_madrid_seccion_completo["Dato base"].str.contains("hogar").map({True: "hogar", False: "persona"})
df_madrid_seccion_completo = df_madrid_seccion_completo.drop(columns=['COD', 'Dato base'])
df_madrid_seccion_completo = df_madrid_seccion_completo.rename(columns={'Seccion censal': 'COD_SEC_MADRID'})
df_madrid_seccion_completo['COD_SEC_MADRID'] = "28079" + df_madrid_seccion_completo['COD_SEC_MADRID'].astype(str)

In [ ]:
print(df_madrid_seccion_completo["Año"].isna().sum())      
print(df_madrid_seccion_completo["COD_SEC_MADRID"].nunique()) 
df_madrid_seccion_completo.head(40)

876
2493

     Año    Valor COD_SEC_MADRID     tipo
0   2015  22948.0     2807901001  persona
1   2015  49363.0     2807901001    hogar
2   2015  15045.0     2807901002  persona
3   2015  29040.0     2807901002    hogar
4   2015  15177.0     2807901003  persona
5   2015  31485.0     2807901003    hogar
6   2015  23663.0     2807901004  persona
7   2015  51772.0     2807901004    hogar
8   2015  21605.0     2807901006  persona
9   2015  42246.0     2807901006    hogar
10  2015  17181.0     2807901007  persona
11  2015  35143.0     2807901007    hogar
12  2015  20021.0     2807901008  persona
13  2015  39366.0     2807901008    hogar
14  2015  18709.0     2807901009  persona
15  2015  35423.0     2807901009    hogar
16  2015  17533.0     2807901011  persona
17  2015  34352.0     2807901011    hogar
18  2015  13780.0     2807901012  persona
19  2015  30061.0     2807901012    hogar
20  2015  12704.0     2807901013  persona
21  2015  23465.0     2807901013    hogar
22  2015  14715.0     2807901014  persona
23  2015  29805.0     2807901014    hogar
24  2015  15855.0     2807901015  persona
25  2015  31826.0     2807901015    hogar
26  2015  17518.0     2807901016  persona
27  2015  34491.0     2807901016    hogar
28  2015  16526.0     2807901018  persona
29  2015  32715.0     2807901018    hogar
30  2015  17548.0     2807901019  persona
31  2015  32785.0     2807901019    hogar
32  2015  14837.0     2807901020  persona
33  2015  29831.0     2807901020    hogar
34  2015  15652.0     2807901021  persona
35  2015  32613.0     2807901021    hogar
36  2015  14393.0     2807901022  persona
37  2015  29888.0     2807901022    hogar
38  2015  11457.0     2807901023  persona
39  2015  23867.0     2807901023    hogar